Cooldown Indicators
reverienest/Walpurgisnacht pull request #20
Opened 2019-10-27 05:16 UTC by nisegami

2019-10-27 14:43 UTC, BrandonShockley requested changes
Also add the mask components to the icons. This will unfortunately require reworking the icon layout, as the mask component masks ALL children. I discovered a vertical layout component that you should be able to use to restack the icons. Leme know if this doesn't make sense.

2019-10-27 14:43 UTC, BrandonShockley commented on Assets/Game/Singletons/SpellMap.cs
> +    private void DecrementCooldown(float deltaTime, int playerNumber, SpellType spellType)
```suggestion
    private void DecreaseCooldown(float deltaTime, int playerNumber, SpellType spellType)
```
I would argue that decrement suggests that you are decreasing the cooldown by a uniform amount each time.

2019-10-27 14:43 UTC, BrandonShockley commented on Assets/Game/Singletons/SpellMap.cs
> +    private Slider[] player1SpellIcons = null;
```suggestion
    private Slider[] player1CooldownSliders = null;
```

2019-10-27 14:43 UTC, BrandonShockley commented on Assets/Game/Singletons/SpellMap.cs
> +    private Slider[] player2SpellIcons = null;
```suggestion
    private Slider[] player2CooldownSliders = null;
```

2019-10-27 15:31 UTC, nisegami commented
suggestions applied

2019-10-27 17:11 UTC, BrandonShockley commented
I should probably stop making direct code suggestions. Check SpellMap.cs. You didn't change the places playerXCooldownSliders and DecreaseCooldown are used, so it doesn't compile. Also you'll need to assign the cooldown slider references in the SpellMap prefab in the main scene again since you changed the name in the script.

2019-10-29 12:50 UTC, BrandonShockley approved these changes

2019-10-29 21:06 UTC, merged